###  問題1】train_test_splitのスクラッチ

スクラッチの練習として、scikit-learnのtrain_test_splitを自作してみます。以下の雛形をベースとして関数を完成させてください。

[sklearn.model_selection.train_test_split — scikit-learn 0.21.3 documentation](https://diver.diveintocode.jp/curriculums/1643)

なお、作成した関数がscikit-learnのtrain_test_splitと同じ動作をしているか必ず確認をするようにしましょう。


In [1]:
import numpy as np
import pandas as pd
import random
import math

In [2]:
def scratch_train_test_split(X, y, train_size=0.8,):
    """
    検証データを分割する。
    Parameters
    ----------
    X : 次の形のndarray, shape (n_samples, n_features)
      訓練データ
    y : 次の形のndarray, shape (n_samples, )
      正解値
    train_size : float (0<train_size<1)
      何割をtrainとするか指定
    Returns
    ----------
    X_train : 次の形のndarray, shape (n_samples, n_features)
      訓練データ
    X_test : 次の形のndarray, shape (n_samples, n_features)
      検証データ
    y_train : 次の形のndarray, shape (n_samples, )
      訓練データの正解値
    y_test : 次の形のndarray, shape (n_samples, )
      検証データの正解値
    """
    #ここにコードを書く
    
    #error handling
    if (X.shape[0] != y.shape[0]):
        print("Check the size of inputs - X is {} & y is {}".format(X.shape[0], y.shape[0]))
    
    #if (y.shape >= 1):
        #print("Check the output of y! Should be an 1d array")
        
    #input data
    n_rows = X.shape[0]
    split = train_size * X.shape[0]
    n_size = X.shape[0] * X.shape[1]
    split_X = train_size
    total_X = math.floor(n_rows * split_X)

    #randomiser - X
    X_mix = []
    X_mix = random.sample(list(X.flatten()), n_size)
    
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            X[i][j] = X_mix[0]
            X_mix.pop(0)

    #randomiser - Y
    y_mix = []
    y_mix = random.sample(list(y.flatten()), len(y))
    
    for i in range(len(y)):
            y[i] = y_mix[0]
            y_mix.pop(0)
    
    combined = np.hstack([X, y.reshape(len(y), 1)])
    
    X_train = combined[:total_X, :-1]
    X_test = combined[total_X:, :-1]
    y_train = combined[:total_X, -1]
    y_test = combined[total_X:, -1]
    
    return X_train, X_test, y_train, y_test

In [3]:
a= np.random.rand(10, 3)
b= np.zeros(10,)
scratch_train_test_split(a, b, train_size=0.8,)

(array([[0.36060852, 0.22856791, 0.85957309],
        [0.14303992, 0.7978552 , 0.23664981],
        [0.52614895, 0.66022136, 0.88751505],
        [0.04300935, 0.3182794 , 0.54379074],
        [0.52294377, 0.06704246, 0.59573162],
        [0.37283366, 0.49702169, 0.1034383 ],
        [0.12204455, 0.00508201, 0.41590464],
        [0.05238058, 0.32118795, 0.78061833]]),
 array([[0.83638742, 0.8493153 , 0.31380623],
        [0.95452797, 0.62874968, 0.03847657]]),
 array([0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0.]))

### 3.scikit-learnを用いて機械学習を行うコードを作成

scikit-learnを使ったコードを作成していきます。

検証データの分割には問題1で作成した自作の関数を用いてください。NB: クロスバリデーションではなくホールドアウト法で構いません。



In [4]:
#SGD
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

#SVM
from sklearn.svm import SVC

#Decision Tree
from sklearn.tree import DecisionTreeClassifier

In [7]:
#Dataset

from sklearn.datasets import load_iris

iris_data = load_iris()

df_new = pd.DataFrame(data=np.c_[iris_data['data'], iris_data['target']], columns=iris_data['feature_names'] + ['labels'])
df_new

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     labels  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

### データセット1

In [34]:
q2_data = df_new[50:][:]
data_1_x = q2_data.iloc[:, :4].to_numpy()
data_1_y = q2_data.iloc[:, -1].to_numpy()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [17]:
iris_data['target_names'][1], iris_data['target_names'][2]

('versicolor', 'virginica')

残り2つは特徴量が2つのデータセットを人工的に用意します。以下のコードで説明変数X,目的変数yが作成可能です。「シンプルデータセット1」「シンプルデータセット2」とします。特徴量が2つであるため可視化が容易です。

### データセット2

In [47]:
import numpy as np
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))
X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)
random_index = np.random.permutation(np.arange(n_samples))
data_2_x = X[random_index]
data_2_y = y[random_index]

data_2_x, data_2_y

(array([[ 7.72382751e-01, -2.29167329e+00],
        [-5.93349449e-01,  1.66788336e+00],
        [-2.07648560e+00,  4.87468451e-01],
        [ 1.19226877e-01,  3.62537974e+00],
        [-3.13000578e+00, -1.56731551e-01],
        [-1.78109832e+00,  1.22224904e+00],
        [ 3.99770982e+00,  1.25164011e+00],
        [ 2.15604470e+00, -3.85824429e-01],
        [ 1.94741552e+00, -1.29638961e+00],
        [ 1.58757396e+00, -1.85989193e+00],
        [ 2.05369045e+00, -9.47185530e-01],
        [-1.97439392e+00,  1.22718715e+00],
        [-3.47487306e+00,  3.70421433e-01],
        [ 1.68094977e+00, -6.36507554e-01],
        [-9.51997101e-01,  1.41989638e+00],
        [-1.23054341e+00,  2.48848983e+00],
        [-6.96789478e-01,  1.88359001e+00],
        [ 1.03842491e+00, -8.88815671e-01],
        [ 3.68706491e+00,  4.30242556e-01],
        [-1.03002856e+00,  1.27865865e+00],
        [-1.26658152e+00,  1.97258945e+00],
        [-1.97638843e-02,  2.54412654e+00],
        [ 8.60592217e-01, -2.461

### データセット3

In [43]:
data_3_x  = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
data_3_y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 【問題2】 分類問題を解くコードの作成

上記3種類の手法で3種類のデータセットを学習・推定するコードを作成してください。

In [41]:
#Dataset 1

X_train_1, X_test_1, y_train_1, y_test_1 = scratch_train_test_split(data_1_x, data_1_y, train_size=0.8,)


#####SGD######
sgd = make_pipeline(StandardScaler(),
                              SGDClassifier(max_iter=1000, tol=1e-3))
sgd_model = sgd.fit(X_train_1, y_train_1)

print(sgd_model.predict(X_test_1))

#####SVM######
#学習
svm = make_pipeline(StandardScaler(), SVC(gamma='auto'))
model_svm = svm.fit(X_train_1, y_train_1)

#推定
print(model_svm.predict(X_test_1))

#####Decision Tree######
#学習
decision_tree = DecisionTreeClassifier(random_state=0)
model_decision_tree = decision_tree.fit(X_train_1, y_train_1)

#推定
print(model_decision_tree.predict(X_test_1))


[2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 1. 2. 1. 1. 1. 1. 1. 2. 2. 1.]
[1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.]
[1. 1. 2. 1. 2. 2. 2. 2. 1. 1. 1. 2. 1. 1. 1. 2. 2. 1. 1. 2.]


In [45]:
#Dataset 2

X_train_2, X_test_2, y_train_2, y_test_2 = scratch_train_test_split(data_2_x, data_2_y, train_size=0.8,)


#####SGD######
sgd = make_pipeline(StandardScaler(),
                              SGDClassifier(max_iter=1000, tol=1e-3))
sgd_model = sgd.fit(X_train_2, y_train_2)

print(sgd_model.predict(X_test_2))

#####SVM######
#学習
svm = make_pipeline(StandardScaler(), SVC(gamma='auto'))
model_svm = svm.fit(X_train_2, y_train_2)

#推定
print(model_svm.predict(X_test_2))

#####Decision Tree######
#学習
decision_tree = DecisionTreeClassifier(random_state=0)
model_decision_tree = decision_tree.fit(X_train_2, y_train_2)

#推定
print(model_decision_tree.predict(X_test_2))


[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 1. -1. -1. -1. -1.  1. -1. -1. -1.  1.  1. -1. -1. -1. -1.  1. -1. -1.
 -1.  1. -1.  1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1.  1. -1.
  1.  1.  1. -1. -1.  1.  1.  1. -1.  1. -1. -1.  1. -1. -1.  1.  1. -1.
 -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.  1. -1.  1. -1.  1.  1. -1.  1.
  1. -1.  1.  1.  1.  1.  1. -1. -1.  1. -1.  1.  1. -1. -1.  1.  1. -1.
 -1.  1.  1. -1. -1.  1.  1.  1.  1. -1.]
[-1.  1.  1.  1. -1. -1. -1. -1.  1.  1.  1.  1.  1. -1. -1.  1. -1. -1.
 -1.  1. -1. -1.  1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.  1. -1. -1.
  1.  1.  1.  1. -1.  1. -1. -1.  1. -1.

In [46]:
#Dataset 3

X_train_3, X_test_3, y_train_3, y_test_3 = scratch_train_test_split(data_3_x, data_3_y, train_size=0.8,)


#####SGD######
sgd = make_pipeline(StandardScaler(),
                              SGDClassifier(max_iter=1000, tol=1e-3))
sgd_model = sgd.fit(X_train_3, y_train_3)

print(sgd_model.predict(X_test_3))

#####SVM######
#学習
svm = make_pipeline(StandardScaler(), SVC(gamma='auto'))
model_svm = svm.fit(X_train_3, y_train_3)

#推定
print(model_svm.predict(X_test_3))

#####Decision Tree######
#学習
decision_tree = DecisionTreeClassifier(random_state=0)
model_decision_tree = decision_tree.fit(X_train_3, y_train_3)

#推定
print(model_decision_tree.predict(X_test_3))

[0. 1. 1. 0. 0. 1. 0. 0.]
[1. 1. 1. 1. 0. 1. 1. 1.]
[1. 1. 0. 1. 0. 1. 1. 0.]


### 回帰問題
回帰は1種類をスクラッチします。

- 線形回帰

線形回帰は勾配降下法を用いて計算するSGDRegressorクラスを利用してください。

データセットは事前学習期間同様にHouse Pricesコンペティションのものを使います。

In [50]:
import os
os.listdir()

['Sprint機械学習スクラッチ入門.ipynb', 'Spring`.pdf', '.ipynb_checkpoints']

In [52]:
train_data = pd.read_csv('train.csv')
train_data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [56]:
data_4_x = pd.concat([train_data['GrLivArea'], train_data['YearBuilt']], axis=1).to_numpy()
data_4_x
data_4_y = train_data['SalePrice'].to_numpy()
data_4_y

array([208500, 181500, 223500, ..., 266500, 142125, 147500])

### 【問題3】 回帰問題を解くコードの作成

線形回帰でHouse Pricesデータセットを学習・推定するコードを作成してください。

In [59]:
X_train_4, X_test_4, y_train_4, y_test_4 = scratch_train_test_split(data_4_x, data_4_y, train_size=0.8,)

#####SGDRegressor######
from sklearn.linear_model import SGDRegressor
sgd_reg = make_pipeline(StandardScaler(),
                              SGDRegressor(max_iter=1000, tol=1e-3))
sgd_reg_model = sgd_reg.fit(X_train_4, y_train_4)

print(sgd_reg_model.predict(X_test_4))


[181170.91440951 180662.1425127  178644.78382958 179500.29907567
 180179.40146942 184687.22661346 188157.38283765 188380.89821217
 181634.90671701 180130.90679808 178136.88555286 181340.43101862
 181591.53209999 178805.65842307 182283.10995506 180813.73819782
 177891.71914751 180743.38618487 187521.10721614 180915.64055011
 179715.42455366 178379.53627155 178424.30156994 186613.39724148
 184077.98775319 189344.9013033  190898.2541219  193251.8789514
 185746.72429312 182809.6836783  187101.67316234 178585.38320811
 181995.10101879 186989.57504193 181531.18346834 185037.55128936
 179787.98150275 185895.62692956 183502.34219813 181051.2538374
 180257.53726965 179751.60683479 180991.55675634 189336.48099021
 179831.8442323  180841.30777904 180465.13034554 180674.30685658
 173031.98552547 179939.69555154 192979.59955998 179154.65104901
 183014.76106754 187384.84237826 178199.00890566 188455.70480487
 190838.63069706 188290.2132944  180591.36138559 179669.80102693
 178326.4235824  179088.590